[package]
name = "breadwallet-core-sys"
version = "0.1.0"
authors = ["Aidan Curtis <aamcurtis@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]

[build-dependencies]
bindgen = "0.53.1"
cmake = "0.1"